apiVersion: v1
kind: Service
metadata:
  name: APP
  labels:
    app: app-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app
  type: LoadBalancer
